# Generated by Django 3.1 on 2022-05-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargerequest',
            name='finish',
            field=models.BooleanField(default=False),
        ),
    ]
