# Generated by Django 3.1 on 2022-05-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='address',
        ),
        migrations.AddField(
            model_name='product',
            name='css_address',
            field=models.FileField(default='none', upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='html_address',
            field=models.FileField(default='none', upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='js_address',
            field=models.FileField(default='none', upload_to=''),
        ),
    ]
