# Generated by Django 3.1 on 2022-05-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220513_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='css_address',
            field=models.FileField(default='none', upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='html_address',
            field=models.FileField(default='none', upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='js_address',
            field=models.FileField(default='none', upload_to='upload/'),
        ),
    ]
