# Generated by Django 3.1 on 2022-05-13 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20220513_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productName',
        ),
    ]
