# Generated by Django 3.1 on 2022-05-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20220513_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='css_address',
            field=models.FileField(default='none', upload_to='FileRestore/templates'),
        ),
        migrations.AlterField(
            model_name='product',
            name='html_address',
            field=models.FileField(default='none', upload_to='FileRestore/templates'),
        ),
        migrations.AlterField(
            model_name='product',
            name='js_address',
            field=models.FileField(default='none', upload_to='FileRestore/templates'),
        ),
    ]
