# Generated by Django 3.1 on 2022-05-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20220515_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='png_address',
            field=models.FileField(default='none', upload_to='FileRestore/static/png'),
        ),
        migrations.AlterField(
            model_name='product',
            name='css_address',
            field=models.FileField(default='none', upload_to='FileRestore/static/css'),
        ),
        migrations.AlterField(
            model_name='product',
            name='js_address',
            field=models.FileField(default='none', upload_to='FileRestore/static/js'),
        ),
    ]
