# Generated by Django 3.1 on 2022-05-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20220515_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=64)),
                ('productName', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='showName',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
