# Generated by Django 3.1 on 2022-05-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('showName', models.CharField(max_length=64)),
                ('wallet', models.IntegerField()),
            ],
        ),
    ]
