# Generated by Django 3.1 on 2022-05-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rechargeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=64)),
                ('date', models.DateTimeField()),
                ('accpet', models.BooleanField()),
            ],
        ),
    ]
