# Generated by Django 3.1 on 2022-05-18 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_rechargerequest_recharge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='rechargeRequest',
        ),
    ]
